apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: vllm-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
      - name: openwebui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        env:
        - name: OPENAI_API_BASE_URL
          value: "http://phi3-service:8000/v1"
        - name: OPENAI_API_KEY
          value: "sk-dummy"
        - name: WEBUI_NAME
          value: "Chat Anstat AI"
        - name: ENABLE_OLLAMA_API
          value: "false"
        - name: ENABLE_OPENAI_API
          value: "true"
