apiVersion: v1
kind: Service
metadata:
  name: gpt-oss-service
  namespace: vllm-chat
spec:
  selector:
    app: mistral-7b
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30180   
  type: NodePort